### PR TITLE
Make Homebrew Cask into an attribute to allow for using adoptopenjdk

### PR DESCRIPTION
**Pull request by Brantone**

### CODE REVIEW

**Comment by Brantone** [comment]
Don't merge yet ... I'm still waiting on tests to complete ... just getting the PR in now so can get some eyes on it.

**Comment by zirkov** [comment]
LGTM!
By the way, Linux build nodes (docker based ones) are using AdoptOpenJdk container as their base (https://github.com/JetBrains/teamcity-docker-minimal-agent/blob/95ae4e7c836ce3199be126edb286f6b1f0e9e15e/ubuntu/Dockerfile#L1), so might make sense to force our Mac nodes to use it by default

**Review by zirkov — APPROVED** [review]

**Comment by Brantone** [comment]
Yeah, subsequent downstream cookbooks will also make use of that.

**Comment by Brantone** [comment]
Need to keep eye on 
https://github.com/sous-chefs/java/pull/547
https://github.com/sous-chefs/java/issues/544

**Pull request merged**
